version: "3"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: always
    network_mode: host
    volumes:
      - ./data/work/:/opt/adguardhome/work/
      - ./AdGuardHome.yaml:/opt/adguardhome/conf/AdGuardHome.yaml
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
