version: "3"

services:
  influxdb:
    image: influxdb:2.2
    container_name: scrutiny-influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb/:/var/lib/influxdb2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-web
    container_name: scrutiny
    restart: always
    depends_on:
      influxdb:
        condition: service_healthy
    ports:
      - 8010:8080
    volumes:
      - ./data/:/opt/scrutiny/config/
    environment:
      - SCRUTINY_WEB_INFLUXDB_HOST=influxdb
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
