version: "3"

services:
  homarr:
    image: ghcr.io/ajnart/homarr
    container_name: homarr
    restart: always
    ports:
      - 8011:7575
    volumes:
      - ./data/:/data/
      - ./data/configs/:/app/data/configs/
      - ./data/icons/:/app/public/icons/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BASE_URL=homarr.adamhl.dev
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
