services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr
    restart: always
    ports:
      - 8011:7575
    volumes:
      - ./data/:/data/
      - ./configs/:/app/data/configs/
      - ./icons/:/app/public/icons/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      BASE_URL: homarr.adamhl.dev
