services:
  librechat:
    container_name: librechat
    image: ghcr.io/danny-avila/librechat-dev
    restart: always
    user: ${UID}:${GID}
    ports:
      - 8004:3080
    volumes:
      - ./images/:/app/client/public/images/
      - ./logs/:/app/api/logs/
    environment:
      ENDPOINTS: openAI
      OPENAI_MODELS: gpt-4o
      DOMAIN_CLIENT: https://librechat.adamhl.dev
      DOMAIN_SERVER: https://librechat.adamhl.dev
      MONGO_URI: mongodb://mongo:27017/LibreChat
      RAG_API_URL: http://librechat-rag-api:8000
    env_file:
      - .env
    depends_on:
      - librechat-rag-api
      - mongo

  librechat-rag-api:
    container_name: librechat-rag-api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite
    restart: always
    environment:
      DB_HOST: pgvector
    env_file:
      - .env
    depends_on:
      - pgvector

  mongo:
    container_name: librechat-mongo
    image: mongo
    restart: always
    command: mongod --noauth
    user: ${UID}:${GID}
    volumes:
      - ./mongo/:/data/db/

  pgvector:
    container_name: librechat-pgvector
    image: ankane/pgvector
    restart: always
    volumes:
      - ./pgvector/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
