services:
  api:
    container_name: LibreChat
    image: ghcr.io/danny-avila/librechat-dev
    restart: always
    user: 1000:1000
    ports:
      - 8004:3080
    volumes:
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
    environment:
      ENDPOINTS: openAI
      OPENAI_MODELS: gpt-4o
      DOMAIN_CLIENT: https://librechat.adamhl.dev
      DOMAIN_SERVER: https://librechat.adamhl.dev
      MONGO_URI: mongodb://mongodb:27017/LibreChat
      RAG_API_URL: http://rag_api:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - rag_api
  mongodb:
    container_name: LibreChat-mongodb
    image: mongo
    restart: always
    command: mongod --noauth
    user: 1000:1000
    volumes:
      - ./data-node:/data/db
  vectordb:
    container_name: LibreChat-vectordb
    image: ankane/pgvector
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
  rag_api:
    container_name: LibreChat-rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite
    restart: always
    environment:
      DB_HOST: vectordb
    env_file:
      - .env
    depends_on:
      - vectordb

volumes:
  pgdata2:
