version: "3"

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    hostname: mqtt
    restart: always
    command: "mosquitto -c /mosquitto-no-auth.conf"
    volumes:
      - ./data/mosquitto/:/mosquitto/
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 8012:8080
    volumes:
      - ./data/zigbee2mqtt/:/app/data/
      - /run/udev:/run/udev:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
