services:
  umami:
    container_name: umami
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: always
    ports:
      - 8005:3000
    environment:
      DATABASE_URL: postgresql://umami:umami@postgres:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: rOn1zvn/ZOf3xtNIKd3R8Rvk+v6n0HkiMZRtc1FkfxE=
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    container_name: umami-postgres
    image: postgres:15-alpine
    restart: always
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  umami-db-data:
