[project]
name = "homelab"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "python-shellrunner>=0.3.0",
]

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.1.0",
    "ruff>=0.0.257",
]

[tool.pdm.scripts]
pyright = {shell = "pyright ."}
ruff = {cmd = "ruff check ."}
lint = {composite = ["pyright", "ruff"]}
format = {cmd = "black ."}

[tool.pyright]
typeCheckingMode = "strict"
exclude = ["__pypackages__/3.10/lib"]
extraPaths = ["__pypackages__/3.10/lib", "lib"]

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.ruff]
line-length = 120
target-version = "py310"
select = ["E", "F", "W", "I", "N", "UP", "BLE", "FBT", "B", "A", "COM", "C4", "T10", "EM", "EXE", "ISC", "ICN", "G",
"INP", "PIE", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SIM", "TID", "TCH", "ARG", "PTH", "ERA", "PL", "PLC", "PLE",
"PLR", "PLW", "TRY", "RUF"]
ignore = ["E501", "INP001"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
