services:
  librechat:
    container_name: librechat
    image: ghcr.io/danny-avila/librechat-dev
    restart: always
    user: 1000:1000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8004:3080
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images/:/app/client/public/images/
      - ./uploads/:/app/uploads/
      - ./logs/:/app/api/logs/
    environment:
      HOST: 0.0.0.0
      MONGO_URI: mongodb://mongo:27017/LibreChat
      RAG_PORT: 8000
      RAG_API_URL: http://librechat-rag-api:8000
    depends_on:
      - librechat-rag-api
      - mongo

  librechat-rag-api:
    container_name: librechat-rag-api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite
    restart: always
    environment:
      DB_HOST: pgvector
      RAG_PORT: 8000
    env_file:
      - .env
    depends_on:
      - pgvector

  mongo:
    container_name: librechat-mongo
    image: mongo
    restart: always
    command: mongod --noauth
    user: 1000:1000
    volumes:
      - ./mongo/:/data/db/

  pgvector:
    container_name: librechat-pgvector
    image: ankane/pgvector
    restart: always
    volumes:
      - ./pgvector/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
