services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart: always
    ports:
      - 8006:8989
    volumes:
      - ./data/:/config/
      - /mnt/storage/Media/:/Media/
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: America/Chicago
