services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale
    restart: always
    privileged: true
    network_mode: host
    command: tailscaled
    volumes:
      - ./data/:/var/lib/
      - /dev/net/tun:/dev/net/tun
      - /lib/modules/:/lib/modules/
