version: "3"

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/:/data/
      - ./config/:/config/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
