version: "3"

services:
  reaction-light:
    image: ghcr.io/eibex/reaction-light
    container_name: reaction-light
    restart: always
    volumes:
      - ./data/:/bot/files/
      - ./config.ini:/bot/config.ini
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
