services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: always
    ports:
      - 8002:80
    volumes:
      - ./filebrowser.db:/database.db
      - /mnt/storage/:/Storage/
    environment:
      FB_ROOT: /Storage/
      FB_NOAUTH: true
