services:
  kavita:
    container_name: kavita
    image: jvmilazz0/kavita
    restart: always
    ports:
      - 8012:5000
    volumes:
      - ./data/:/kavita/config/
      - /home/adam/mnt/storage/Stuff/Library/:/Library/
