services:
  dashdot:
    container_name: dashdot
    image: mauricenino/dashdot
    restart: always
    privileged: true
    ports:
      - 8005:3001
    volumes:
      - /:/mnt/host/:ro
    environment:
      DASHDOT_SHOW_DASH_VERSION: bottom_right
      DASHDOT_ACCEPT_OOKLA_EULA: true
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_FS_VIRTUAL_MOUNTS: mergerfs
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: true
      DASHDOT_NETWORK_LABEL_LIST: type,speed_up,speed_down,interface_speed,public_ip
      DASHDOT_OVERRIDE_OS: Debian sid
