services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - 8007:7878
    volumes:
      - ./data/:/config/
      - /mnt/storage/Media/:/Media/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
