services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    restart: always
    network_mode: host
    volumes:
      - ./data/:/data
      - ./config/:/config
      - /home/adam/mnt/storage/Media/:/Media/
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK=002
      - TZ=America/Chicago
      - WEBUI_PORTS=8003/tcp,8003/udp
