services:
  ddns-route53-adamhl.dev:
    container_name: ddns-route53-adamhl.dev
    image: crazymax/ddns-route53
    restart: always
    environment:
      SCHEDULE: 0 * * * *
      DDNSR53_CREDENTIALS_ACCESSKEYID: ${aws_access_key_id}
      DDNSR53_CREDENTIALS_SECRETACCESSKEY: ${aws_secret_access_key}
      DDNSR53_ROUTE53_HOSTEDZONEID: Z0001576IKPKC1SOE3BS
      DDNSR53_ROUTE53_RECORDSSET_1_NAME: "*.adamhl.dev"
      DDNSR53_ROUTE53_RECORDSSET_1_TYPE: A
      DDNSR53_ROUTE53_RECORDSSET_1_TTL: 60
