#!/bin/bash

sed -i '1iTo: adamhl@pm.me' ~/restic/restic.log
sed -i '2iFrom: msmtp@adamhl.dev' ~/restic/restic.log
sed -i '3iSubject: [restic-backup] ERROR' ~/restic/restic.log
sops exec-env ~/homelab/secrets.env "msmtp -C ~/msmtp/msmtp.conf --passwordeval='echo \${smtp_password}' -t < ~/restic/restic.log"