"use strict";
module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 16,
    fontFamily: '"JetBrainsMono Nerd Font", monospace',
    fontWeight: "normal",
    fontWeightBold: "bold",
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: "#cccccc",
    cursorAccentColor: "#000",
    cursorShape: "BEAM",
    cursorBlink: true,
    foregroundColor: "#cccccc",
    backgroundColor: "#181818",
    selectionColor: "#264f7875",
    borderColor: "#ffffff15",
    css: "",
    termCSS: "",
    workingDirectory: "",
    showHamburgerMenu: "",
    showWindowControls: "",
    padding: "12px 14px",
    colors: {
      black: "#000000",
      red: "#cd3131",
      green: "#0dbc79",
      yellow: "#e5e510",
      blue: "#2472c8",
      magenta: "#bc3fbc",
      cyan: "#11a8cd",
      white: "#e5e5e5",
      lightBlack: "#666666",
      lightRed: "#f14c4c",
      lightGreen: "#23d18b",
      lightYellow: "#f5f543",
      lightBlue: "#3b8eea",
      lightMagenta: "#d670d6",
      lightCyan: "#29b8db",
      lightWhite: "#e5e5e5",
      limeGreen: "#32CD32",
      lightCoral: "#F08080",
    },
    shell: "/opt/homebrew/bin/fish",
    shellArgs: ["--login"],
    env: {},
    bell: "SOUND",
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: "vertical",
    webGLRenderer: true,
    webLinksActivationKey: "",
    disableLigatures: true,
    disableAutoUpdates: false,
    screenReaderMode: false,
    preserveCWD: true,
  },
  plugins: [],
  localPlugins: [],
  keymaps: {},
};
//# sourceMappingURL=config-default.js.map
