services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex
    restart: always
    network_mode: host
    devices:
      - /dev/dri/
    volumes:
      - ./data/:/config/
      - /mnt/storage/Media/:/Media/
      - /mnt/storage/Other/Z/Z/:/Z/
    environment:
      VERSION: latest
      PUID: ${UID}
      PGID: ${GID}
      TZ: America/Chicago
