linters:
  enable-all: true
  disable:
    - gofumpt
    - depguard
    - gci
    - exhaustruct
    - forbidigo
    # deprecated
    - exportloopref
    - gomnd
    - execinquery

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
