version: "3"

services:
  caddy:
    build: .
    container_name: caddy
    restart: always
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./users.json:/etc/caddy/users.json
      - /home/adam/ez/:/ez/
      - ./data/:/data/
      - ./config/:/config/
    environment:
      - AWS_ACCESS_KEY_ID=AKIAT5NKIWDOTLLLZ34R
      - AWS_SECRET_ACCESS_KEY=${aws_secret_access_key}
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
