build:
  go build

lint:
  gofumpt -extra -w .
  golangci-lint run

run:
  go run .

bump-deps:
  go get -u -t all && go mod tidy

publish-image:
  KO_DOCKER_REPO=ghcr.io/adamhl8 ko build . --platform linux/amd64
