services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    restart: always
    network_mode: host
    volumes:
      - ./data/:/config/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
