version: "3"

services:
  discord-app-bot:
    image: ghcr.io/adamhl8/discord-app-bot
    container_name: discord-app-bot
    restart: always
    volumes:
      - ./data/:/app/data/
    environment:
      - BOT_TOKEN=${discord_app_bot_token}
      - APPLICATION_ID=970956137157492786
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
