services:
  discord-app-bot:
    container_name: discord-app-bot
    image: ghcr.io/adamhl8/discord-app-bot
    restart: always
    volumes:
      - ./data/:/app/prisma/db/
    environment:
      BOT_TOKEN: ${discord_app_bot_token}
      APPLICATION_ID: 970956137157492786
      DATABASE_URL: file:db/prod.db
