services:
  unifi-network-application:
    container_name: unifi-network-application
    image: lscr.io/linuxserver/unifi-network-application
    restart: always
    network_mode: host
    volumes:
      - ./data/:/config/
    environment:
      MONGO_DBNAME: unifi
      MONGO_USER: unifi
      MONGO_PASS: unifi
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      PUID: ${UID}
      PGID: ${GID}
      TZ: America/Chicago
    depends_on:
      - mongo

  mongo:
    container_name: unifi-network-application-mongo
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/:/data/db/
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
