services:
  eyir:
    image: ghcr.io/adamhl8/eyir
    container_name: eyir
    restart: always
    volumes:
      - /home/adam/dev/eyir/faq/:/app/faq/
      - ./data/:/app/prisma/db/
    environment:
      - BOT_TOKEN=${eyir_token}
      - APPLICATION_ID=320863841548238848
      - DATABASE_URL=file:db/prod.db

  filebrowser:
    image: filebrowser/filebrowser
    container_name: eyir-filebrowser
    restart: always
    ports:
      - 8003:80
    volumes:
      - ./data/filebrowser.db:/database.db
      - /home/adam/dev/eyir/faq/:/faq/
    environment:
      - FB_ROOT=/faq/
