version: "3"

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ./data/:/config/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
