services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: always
    ports:
      - 8016:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_REMOTE_AGENT: pi.lan:7007
