"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_macchiato'

format = """
$os\
$username\
$hostname\
$container\
$directory\
$bun\
$nodejs\
$rust\
$golang\
${custom.uv_python}\
$java\
$gradle\
$git_branch\
$git_status\
$jobs\
$time\
[ ](fg:surface1)"""

right_format = """
[](fg:surface1)\
$status\
$cmd_duration\
"""

[status]
disabled = false
pipestatus = true
style = 'fg:text bg:surface1'
success_symbol = '[]($style bold fg:green)'
symbol = '[]($style bold fg:red)'
format = '[ $symbol $int( \($common_meaning$signal_name\)) ]($style)'
pipestatus_segment_format = "$int"
pipestatus_format = '[ $symbol $int( \($common_meaning$signal_name\)) $pipestatus ]($style)'

[cmd_duration]
style = "bg:yellow fg:crust"
format = "[ $duration ]($style)"
min_time = 500
show_milliseconds = true

[os]
disabled = true
style = "bg:subtext0 fg:crust"
format = '[ $symbol( $codename)( $edition)( $version) ]($style)'

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
style_user = "bg:green fg:crust"
style_root = "bold bg:red fg:crust"
format = '[ $user ]($style)'

[hostname]
trim_at = ""
style = "bg:mauve fg:crust"
format = '[ $hostname ]($style)'

[container]
style = "bg:blue fg:crust"
format = '[ $symbol \[$name\] ]($style)'

[directory]
truncation_length = 0
truncate_to_repo = false
style = "bg:sky fg:crust"
read_only_style = "bg:teal fg:crust"
read_only = ""
format = '[ $path ]($style)([$read_only ]($read_only_style))'

[bun]
symbol = ""
style = "bg:peach fg:crust"
format = '[ $symbol( $version) ]($style)'

[nodejs]
symbol = ""
style = "bg:peach fg:crust"
not_capable_style = "bold bg:peach fg:c_red"
format = '[ $symbol ](bg:peach fg:crust)([$version ]($style))'

[rust]
symbol = ""
style = "bg:peach fg:crust"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = "󰟓"
style = "bg:peach fg:crust"
not_capable_style = "bold bg:peach fg:c_red"
format = '[ $symbol ](bg:peach fg:crust)([$version ]($style))'

[custom.uv_python]
command = 'uv python find --show-version'
detect_files = ['.python-version', 'pyproject.toml', 'uv.lock']
symbol = ""
style = "bg:peach fg:crust"
format = '[ $symbol( $output) ]($style)'

[java]
symbol = ""
style = "bg:peach fg:crust"
format = '[ $symbol( $version) ]($style)'

[gradle]
symbol = ""
style = "bg:maroon fg:crust"
format = '[ $symbol( $version) ]($style)'

[git_branch]
symbol = ""
style = "bg:yellow fg:crust"
format = '[ $symbol $branch ]($style)'

[git_status]
stashed = '[*$count](bg:yellow fg:c_green) '
untracked = '[?$count](bg:yellow fg:c_purple) '
conflicted = '[=$count](bg:yellow fg:c_purple) '
deleted = '[$count](bg:yellow fg:c_red) '
renamed = '[»$count](bg:yellow fg:c_blue) '
modified = '[!$count](bg:yellow fg:c_blue) '
staged = '[+$count](bg:yellow fg:c_green) '
ahead = '[⇡$count](bg:yellow fg:c_green) '
behind = '[⇣$count](bg:yellow fg:c_purple) '
diverged = '[⇡${ahead_count}](bg:yellow fg:c_green)[⇣${behind_count}](bg:yellow fg:c_purple) '
style = 'bg:yellow fg:crust'
format = '[($all_status$ahead_behind)]($style)'

[jobs]
style = "bg:surface1 fg:text"
symbol = "&"
format = '[ $symbol$number ]($style)'

[time]
disabled = false
time_format = '%-I:%M:%S%P'
style = 'bg:surface1 fg:text'
format = '[ $time ]($style)'

[palettes.catppuccin_macchiato]
c_red = "#BA0000"
c_green = "#006600"
c_blue = "#0066cc"
c_purple = "#990099"
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
