version: "3"

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: always
    command: serve
    ports:
      - 8008:80
    volumes:
      - ./data/ntfy/:/etc/ntfy/
      - ./data/cache/:/var/cache/ntfy/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
