services:
  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - 9000:80
    volumes:
      - ./data/:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  mysql:
    container_name: wordpress-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./mysql/:/var/lib/mysql
