services:
  syncthing:
    container_name: syncthing
    image: syncthing/syncthing
    restart: always
    command: -no-default-folder
    ports:
      - 8001:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - ./data/:/var/syncthing/
      - /home/adam/mnt/storage/Stuff/:/Stuff/
