services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: always
    command: -no-default-folder
    ports:
      - 8001:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - ./data/:/var/syncthing/
      - /mnt/storage/Stuff/:/Stuff/
      - /mnt/storage/Apps/:/Apps/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
