services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: always
    ports:
      - 8013:8000
    volumes:
      - ./data/:/usr/src/paperless/data
      - /mnt/storage/Paperless/:/usr/src/paperless/media
      - ./export/:/usr/src/paperless/export
      - ./consume/:/usr/src/paperless/consume
    environment:
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_URL: https://paperless.adamhl.dev
      PAPERLESS_SECRET_KEY: ${paperless_secret_key}
      PAPERLESS_TIME_ZONE: America/Chicago
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_FILENAME_FORMAT: "{created_year}{created_month}{created_day} {title}"
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_OCR_USER_ARGS: '{"continue_on_soft_render_error": true}'
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: always
      PAPERLESS_DBHOST: postgres
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
    healthcheck:
      test:
        ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
      - redis
      - tika
      - gotenberg

  postgres:
    image: docker.io/library/postgres:15
    container_name: paperless-ngx-postgres
    restart: always
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  redis:
    image: docker.io/library/redis:7
    container_name: paperless-ngx-redis
    restart: always
    volumes:
      - ./data/redis/:/data

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: paperless-ngx-tika
    restart: always

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    container_name: paperless-ngx-gotenberg
    restart: always
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
