services:
  watchtower:
    container_name: watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: containrrr/watchtower
    restart: always
    ports:
      - 8020:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_TOKEN=${watchtower_api_token}
