linters:
  enable-all: true
  disable:
    - gofumpt
    - depguard
    - gci
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    # deprecated
    - exportloopref

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
