build:
  go build -o ~/bin/dns-overrides

lint:
  gofumpt -extra -w .
  golangci-lint run

run:
  go run .

bump-deps:
  rm -f go.sum
  go clean -cache
  go clean -modcache
  go get -u -t
  go mod tidy
  go get -u -t all
  go mod tidy
